source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"


target '百思不得姐' do
    pod 'AFNetworking'
    pod 'SDWebImage'
    pod 'MJRefresh'
    pod 'Masonry'
    pod 'JSONModel'
    pod 'ProgressHUD'
end
